---

# R1:
#     hostname: "192.168.10.11"
#     groups:
#         - cisco_group
#     data:
#         ntp_server: "1.1.1.1"
    

# R2:
#     hostname: "192.168.10.12"
#     groups:
#         - cisco_group
#     data:
#         ntp_server: "2.2.2.2"

# R3:
#     hostname: "192.168.10.13"
#     groups:
#         - cisco_group
#     data:
#         ntp_server: "3.3.3.3"

# R4:
#     hostname: "192.168.10.14"
#     groups:
#         - cisco_group
#     data:
#         ntp_server: "4.4.4.4"
R5:
    hostname: 192.168.10.19
    password: cisco